import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AntiPatternResult } from './analyzer';

export function generatePDF(filename: string, results: AntiPatternResult[]) {
    const doc = new jsPDF();

    // Color Palette colors (approximate RGB implementation for PDF)
    const colors = {
        black: [10, 10, 10], // #0a0a0a
        darkGray: [24, 24, 27], // zinc-900
        lightGray: [161, 161, 170], // zinc-400
        electricLime: [204, 255, 0], // #ccff00
        high: [239, 68, 68], // red-500
        medium: [249, 115, 22], // orange-500
        low: [59, 130, 246], // blue-500
    };

    // --- Header ---
    doc.setFillColor(colors.black[0], colors.black[1], colors.black[2]);
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('times', 'bold');
    doc.text('The Code Refinery', 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(colors.electricLime[0], colors.electricLime[1], colors.electricLime[2]);
    doc.text('STATIC ANALYSIS REPORT', 14, 28);

    const dateStr = new Date().toLocaleDateString();
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated: ${dateStr}`, 196, 20, { align: 'right' });
    doc.text(`File: ${filename}`, 196, 28, { align: 'right' });

    // --- Summary Section ---
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 14, 55);

    const highCount = results.filter(r => r.severity === 'high').length;
    const mediumCount = results.filter(r => r.severity === 'medium').length;
    const lowCount = results.filter(r => r.severity === 'low').length;

    // Draw Summary Boxes
    // High
    doc.setFillColor(colors.high[0], colors.high[1], colors.high[2]);
    doc.rect(14, 60, 4, 15, 'F');
    doc.setFontSize(12);
    doc.text('High Severity', 22, 66);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${highCount} issues`, 22, 72);

    // Medium
    doc.setFillColor(colors.medium[0], colors.medium[1], colors.medium[2]);
    doc.rect(70, 60, 4, 15, 'F');
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Medium Severity', 78, 66);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${mediumCount} issues`, 78, 72);

    // Low
    doc.setFillColor(colors.low[0], colors.low[1], colors.low[2]);
    doc.rect(130, 60, 4, 15, 'F');
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Low Severity', 138, 66);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`${lowCount} issues`, 138, 72);


    // --- Detailed Table ---
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Detailed Findings', 14, 95);

    const tableData = results.map(r => [
        r.line.toString(),
        r.severity.toUpperCase(),
        r.name,
        r.description,
        r.message
    ]);

    autoTable(doc, {
        startY: 100,
        head: [['Line', 'Severity', 'Pattern', 'Issue', 'Recommendation']],
        body: tableData,
        theme: 'grid',
        headStyles: {
            fillColor: colors.black as [number, number, number],
            textColor: [255, 255, 255],
            fontStyle: 'bold',
        },
        styles: {
            fontSize: 9,
            cellPadding: 3,
            overflow: 'linebreak'
        },
        columnStyles: {
            0: { cellWidth: 15, halign: 'center' }, // Line
            1: { cellWidth: 20, fontStyle: 'bold' }, // Severity
            2: { cellWidth: 35, fontStyle: 'bold' }, // Pattern
            3: { cellWidth: 60 }, // Issue
            4: { cellWidth: 'auto' } // Recommended Fix
        },
        didParseCell: (data) => {
            // Color code the severity column text
            if (data.section === 'body' && data.column.index === 1) {
                const severity = data.cell.raw as string;
                if (severity === 'HIGH') {
                    data.cell.styles.textColor = colors.high as [number, number, number];
                } else if (severity === 'MEDIUM') {
                    data.cell.styles.textColor = colors.medium as [number, number, number];
                } else {
                    data.cell.styles.textColor = colors.low as [number, number, number];
                }
            }
        }
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount}`, 196, 290, { align: 'right' });
        doc.text('Generated by The Code Refinery', 14, 290);
    }

    doc.save(`${filename.replace(/\.[^/.]+$/, "")}-analysis-report.pdf`);
}
